### ISSUE TITLE
Documentation missing images

### ISSUE THREAD

**Issue by eugenevdm** [secondimpression/whmcs-freeradius#3]
I searched for documentation and found Steven's blog here:

http://secondimpression.net/post/29334865544/new-whmcs-freeradius-template-files

However, all the images are missing making it a bit difficult to understand all the features. I would be mighty fine if we can have some of the images back.

**Comment by davidchua** [comment]
Seconding the documentation. I've installed it and I think I've configured it but I'm getting a blank screen when a user attempts to order the WHMCS product on the portal.

**Comment by eksoverzero** [comment]
Closing in favour of #13 and #14
