### ISSUE TITLE
freeradius_username function does not exist in refactor branch for the freeradius.php file

### ISSUE THREAD

**Issue by VerheireNiel** [secondimpression/whmcs-freeradius#35]
Seems like this function is missing which breaks the module. I copied over the function from the master and succesfully created my user through whmcs.

**Comment by mabangjy** [comment]
@VerheireNiel Hello, can I share a code for me? I cannot created my user through whmcs.

**Comment by VerheireNiel** [comment]
@mabangjy Hi, just copy over the function found in the master branch to the one from the refactor branch.

https://github.com/eksoverzero/whmcs-freeradius/blob/master/freeradius.php
Line: 76

It is a work in progress as noted by @eksoverzero so not everything is functional. There are also some variables missing so if you don't know how WHMCS/PHP works you should wait for the full version.

**Comment by mabangjy** [comment]
@VerheireNiel Thank you. You're right. I should wait for the full version. I hope it will come soon.

**Comment by kenarsuleyman** [comment]
@VerheireNiel Does this modification is enough for get it work with whmcs 7.4 ? Or which whmcs version should i downgrade?

**Comment by imhinotori** [comment]
@Virinom WHMCS 7.4 changed how handle the api to a more restricted one, downgrade to 7.3 and it should work

**Comment by eksoverzero** [comment]
@VerheireNiel, I have moved the function over to the refactor branch.

Thanks for trying to run the refactor branch, WHMCS has taken away my developer license because I don't have a paid license so testing is a little tricky for me at the moment.
