### ISSUE TITLE
FreeRADIUS Database Query Error

### ISSUE THREAD

**Issue by imhinotori** [secondimpression/whmcs-freeradius#36]
When trying to accept a client from WHMCS (7.3) throw this error: "FreeRADIUS Database Query Error" without nothing more.

**Comment by eksoverzero** [comment]
Are you using code from the master or refactor branch?

**Comment by imhinotori** [comment]
Sorry the late response, i already make it work <3, im using the refactor branch.

Thanks a lot 4 your work
